#!/usr/bin/env bash
# this trasnfers a file from our client to a server if the system 
# arguments are greater than or equal to 4 else prints out the usage instruction
if [ $# -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
