#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page
# https://www.youtube.com/watch?v=QH2-TGUlwu4

# Install Nginx web server
sudo apt update
sudo apt install nginx -y

# Configure redirect
sudo sed -i '/^http {/a
    server {
        listen 80;
        server_name 54.157.147.18;
        
        location /redirect_me/ {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
    }' /etc/nginx/nginx.conf

# Test configuration file for syntax errors
sudo nginx -t

# Reload Nginx to apply the new configuration
sudo service nginx reload

