#!/usr/bin/env bash
#Configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get -y update
apt-get -y install nginx
service nginx start
new_string="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://yooutube.com/;\n\t}\n"

sed -i "s|server_name _;|${new_string}|" /etc/nginx/sites-available/default
service nginx restart
