#!/usr/bin/env bash
# displays the contents of etc/passwd, onlly displaying usernmae, user id
# and user home direcctory

while read -r passwd;
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
