#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration
# displays Best School and then Hi on a new line, makes use of a while and if

i=0
while [ $i -le 9 ]
do
	echo "Best School"
	if [ $i == 8 ]
	then
		echo "Hi"
	fi
	((i++))
done
