#!/usr/bin/env bash
# sets up Nginx to run nginx user
pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
